### ISSUE TITLE
ACF Options page

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#112]
Hi there,

How can I get the ACF options page information? For instance; I store my WordPress menu there, and need to fetch it on every page.

**Comment by northosts** [comment]
Hi, WUXT only includes the values of ACF fields added to posts by default. I would recommend to install the "ACF to REST API" plugin https://github.com/airesvsg/acf-to-rest-api in the WordPress backend and use its endpoints for options pages to get the requested information.

**Comment by simplenotezy** [comment]
Thanks @northosts
