### ISSUE TITLE
Setting up the frontend

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#114]
I got the Wuxt development server up and running - great.

Now I need to start writing components and setting up the frontend. As far as I can see, theres no documentation on this. I guess I simply need to setup a webpack config, including Vue2, babel etc, or is there some specific recommended approach to this?

**Comment by simplenotezy** [comment]
The more I think about it, the more confused I get. I am really not sure how to proceed with this library. How/where do I write all my Vue Components and logic?

Do I setup a new node.js server and fetch data from http://localhost:3000? I'd like the WordPress environment and Vue.js application to be seperate. But if I am supposed to fetch data from http://localhost:3000, then why would you have implemented browser-sync?

**Comment by northosts** [comment]
Hi everything is compiled on the fly inside the nuxt docker-container, when you changing the files in you lokal directory (which is mountet as a volume inside the container). If everything works correctly you should see frontens-changes instantly at the localhost url.

**Comment by northosts** [comment]
Inside the root-folder of the project you have a nuxt-folder. Here you are creating all your nuxt-stuff. In the same place you have a wp-content folder, where you add all WordPress stuff. the two folders are mountet as volumes into their docker container (one for nuxt, one for wp). Inside the nuxt-container runs the nuxt dev-server. If everything works correctly you can open both wp-admin and nuxt with localhost:port urls in your local webbrowser. Should be described in the README.md file as well, see even quick-start guide.

**Comment by simplenotezy** [comment]
Hey @northosts, thanks. I have located the nuxt folder now, and that makes a lot more sense now.

I am trying to get things up and running. I did see the quick start guide, but perhaps some information is missing in regards to the "/nuxt/" folder, and this should be where your frontend code should be. Anyhow, it makes a lot more sense now, thanks! 😊

**Comment by northosts** [comment]
You're welcome
