### ISSUE TITLE
WP_Debug / wp-config

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#115]
Where do I customize the wp-config.php? I am currently experincing some errors, and the page is just white.

**Comment by northosts** [comment]
Hi, you can define wp-config.php constants in the docker-compose.yml file, like this: 

    WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://localhost:${WUXT_PORT_BACKEND:-3080}' );
        define('WP_HOME', 'http://localhost:${WUXT_PORT_BACKEND:-3080}' );

It's dokumentet in the official WordPress Dockerfile docs. Don't forget to run `docker-compose up` after changing the file
