### ISSUE TITLE
Getting "ERR_EMPTY_RESPONSE" on http://localhost:3000/ 

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#117]
After booting up docker, I get the error: "ERR_EMPTY_RESPONSE"

![image](https://user-images.githubusercontent.com/3786627/74022900-c4954a00-499e-11ea-96fe-f95e8f75ba74.png)

I experienced the error after dowing and then upping the docker server. I didn't change anything, and it just happened out of the blue.

I managed to get the page back, after messing around with `yarn install` and `yarn run dev` inside the /nuxt/ folder, but after downing the server again ( to change Docker resources ), now after booting up again, I can't access the front end.

I have no other browsersync/etc running on port 3000 atm. I can access the WordPress backend without any issues.

**Comment by simplenotezy** [comment]
After waiting a bit, and then refreshing the page, now it loads. So it only happens sometimes / perhaps after a reboot of the docker instance.

**Comment by simplenotezy** [comment]
Ah.. Now it's the http://localhost:3080/wp-admin/ I can't access. I am getting: `ERR_CONNECTION_REFUSED`

**Comment by northosts** [comment]
If you change server files in nuxt, the backend is recompiling which might take down the environment for a bit. The WordPress-container shouldn't take more than a few seconds to restart and be available at localhost. Might be some PHP error?

**Comment by simplenotezy** [comment]
Yes, `http://localhost:3080/wp-admin/` is up now. It takes a few seconds to boot up I guess. However, I still can't access http://localhost:3000/  :(

**Comment by simplenotezy** [comment]
I just tried rebooting my computer to see if it would fix anything, but it didn't. Very strange, because it worked initially out of the box. WordPress admin works fine, but the frontend does not.

**Comment by simplenotezy** [comment]
Strange. After trying another refresh it works again. Hmm...

**Comment by danielauener** [comment]
@simplenotezy ok, in my experience it can take a while until the Nuxt frontend is compiled and available, we had even some memory and volume sync issues reported. Will close this issue now, thanks for reporting!
