### ISSUE TITLE
Very slow development environment

### ISSUE THREAD

**Issue by simplenotezy** [northosts/wuxt#119]
When using the /wp-admin/ on a fresh install, it's okay speed. But as soon as you start to install some plugins (WPML, WooCommerce, etc) the speed slows down **alot**.

Even using the wp-rest api, will take a few seconds to respond.

I have tested out, using a different, yet popular, docker image: https://github.com/visiblevc/wordpress-starter

It's blazingly fast.

My suggestion is: **Let's base wuxt on the setup that visiblevc/wordpress-starter has. I think this would create a much faster and more pleasant development environment.**

Heres a comparrsion.

Using northosts/wuxt docker:
=====
![image](https://user-images.githubusercontent.com/3786627/74027496-8ef55e80-49a8-11ea-8323-135e17245584.png)

Using visiblevc/wordpress-starter docker:
=====
![image](https://user-images.githubusercontent.com/3786627/74026930-805a7780-49a7-11ea-890d-3902818862c2.png)

I found the library through this SO question, and the answer explains why visblevs/wordpress-starter might be so fast: https://stackoverflow.com/questions/54291859/docker-wordpress-super-slow

**Comment by samuelhorn** [comment]
I would try adding :rw,cached to line 17 in docker-compose.yml like:
          - ./wp-content:/var/www/html/wp-content:rw,cached

then restart.

Tell me if that helps and i will make a PR.

**Comment by shmuel-web** [comment]
@samuelhorn 
thanks for the fix much faster now :)

**Comment by danielauener** [comment]
@samuelhorn nice catch! Would love to merge a PR!

**Comment by samuelhorn** [comment]
@shmuel-web no problem, glad to help! :)

@danielauener incoming!
