### ISSUE TITLE
Overloaded?

### ISSUE THREAD

**Issue by gazdajezda** [northosts/wuxt#143]
Hello!

I run 6 instances od Wuxt on my Linux server (i try to make Wuxt to be CMS like for managing content, which will be staticaly served). I run 6 containers and when they all run, after some time randomly in one of two of them just crashed:

test3-front.wuxt | ✔ Builder initialized
test3-front.wuxt | ✔ Nuxt files generated
test3-front.wuxt | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
test3-front.wuxt | ℹ Compiling Client
test3-front.wuxt | ℹ Compiling Server
test3-front.wuxt | (node:68) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
test3-front.wuxt | ✔ Server: Compiled successfully in 9.99s
test3-front.wuxt | ✔ Client: Compiled successfully in 11.92s
test3-front.wuxt | ℹ Waiting for file changes
test3-front.wuxt |
test3-front.wuxt |  READY  Server listening on http://0.0.0.0:3000
test3-front.wuxt |
**test3-front.wuxt | [nodemon] app crashed - waiting for file changes before starting...**

Do anyone know what could be the reason for that? Thankx!

**Comment by danielauener** [comment]
Hi, have you checked your memory consumption? Might be worth a shot to take a look at `docker stats` as well to get more information. Same problem when you run just 3 Wuxt instances?

**Comment by gazdajezda** [comment]
Hi!

Thank you for your response. In fact, you are right, memory was the
problem. I raise memory alocation for that particular VM and it is better.
I still learning it, but at the moment that issue is gone :-)

Best regards!
