### ISSUE TITLE
Install webpack loaders for pre-processors

### ISSUE THREAD

**Issue by samuelhorn** [northosts/wuxt#2]
I think, by default these libs & loaders should be installed on the node container, so one can use `lang="scss"` on style tags in vue components:

`yarn add node-sass sass-loader -D`

[Read more in Nuxt docs](https://nuxtjs.org/faq/pre-processors/)

If i run it in ./nuxt to mirror it to the container everything stops working. For me, I had to SSH into the node container, install it, and then restart docker to get it working.

**Comment by northosts** [comment]
all possible nuxt preprocessors added (86117dc), restarting the nuxt container will make them active. Regarding installing packages from the host:

Some files (in this case `yarn.lock`) are generated inside the container, with the containers user (which is root). that means that these files are owned by root even on the host, which can cause issues when you're trying to change the files with your user. I'll try to find a solution in some way, right now changing file permissions manually on the host might work, or as you did, switching to the container and install packages there.

**Comment by northosts** [comment]
Now, we have added some easy gulp tasks to install yarn packages and managing wp. Checkout the section Task Management -> Working with the containers in the docs for more info. Just basic stuff right now, but more is comming!

Closing the issue, thanks for reporting!
