### ISSUE TITLE
Documentation about how to get custom post type meta to the API

### ISSUE THREAD

**Issue by samuelhorn** [northosts/wuxt#3]
When you make a new custom post type, and want it and its ACF & Yoast meta fields to show in the API you have to:

1. Support custom fields in the post type: 
`'supports' => array('custom-fields')`
2. Support rest in the post type: 
`'show_in_rest' => true`
3. Make the `wuxt_register_acf_meta()` register meta for the new post type as well:
`register_post_meta('recommendation', $field['name'], array('show_in_rest' => true));`
4. Do the same in the `wuxt_register_yoast_meta()`: 
`register_post_meta('recommendation', $field, array('show_in_rest' => true));`
5. Add stuff to the `nuxt/modules/wp-api/plugin.js`: 
`import registerRecommendation from '~/modules/wp-api/routes/recommendation'`
6. Add more stuff to the same file:
`registerRecommendation(wp)`
6. Make a new file `nuxt/modules/wp-api/routes/recommendation.js`: 
```
export default wp =>
  (wp.recommendation = wp.registerRoute('wp/v2', '/recommendation/(?P<id>)', {
    params: ['embed']
  }))
```

Maybe this can be simplified somehow, but at least it needs to be documented. 🤓

**Comment by northosts** [comment]
thanks for reporting, there are new custom post type function which should solve all the mentioned problems. If you create your post types with scaffolding (see docs) everything is setup the right way. Querying post types from nuxt is made much more easier with the new `cpt` method, documented in the WordPress API endpoints section.

Good luck!
