### ISSUE TITLE
/wp-json/wuxt/v1/generate endpoint can't be access

### ISSUE THREAD

**Issue by alvinlabrador** [northosts/wuxt#47]

**Comment by alvinlabrador** [comment]
![image](https://user-images.githubusercontent.com/51313388/64935504-45369b00-d884-11e9-838a-a1c15ce6d13d.png)

**Comment by northosts** [comment]
Thanks for the issue. Unfortunately I cannot reproduce this. Guessing that you missed one step in the setup process. Check if you did everything under "Quick Start" https://github.com/northosts/wuxt#quick-start. Otherwise: Are WordPress core api routes working, are other wuxt api routes working?

**Comment by alvinlabrador** [comment]
I tried to use the one from wordpress https://wordpress.org/plugins/wuxt-headless-wp-api-extensions/ I thought it's the same. It's now working properly when I used the one from the repo. Thanks for the response. Cheers
