### ISSUE TITLE
asyncData not working?

### ISSUE THREAD

**Issue by baxgas** [northosts/wuxt#60]
I want to rewrite the working .fetch function to asyncData (to store the pages on the server), but it somehow doesn't work. I tried with the dummy json palceholder for now, but it doesn't return anything. Any idea why?

```
export default {

async asyncData({ $axios }) {
  const data = await $axios.$get('https://jsonplaceholder.typicode.com/todos/1')
  faketitle = this.data.title;
},

components: {
    Logo
  },
  data() {
    return { 
      menus: [],
      hostAdress: hostAdress,
      faketitle: ''
      }
  },
  mounted() { 
    fetch(hostAdress + '/wp-json/wuxt/v1/menu')
    .then(response => {
      response.json().then(menus => {
        this.menus = menus;
      })
    })
  }

}
```

**Comment by northosts** [comment]
Hi, you have to return something from asyncData. like:

```javascript
async asyncData({ $axios }) {
  const data = await $axios.$get('https://jsonplaceholder.typicode.com/todos/1')
  return { 
    faketitle: data.title
  }; 
},
```

Hope that helps!

**Comment by baxgas** [comment]
Thanks, but somehow asyncData doesn't work in my case :-( 
I tried with axios on mounted() with this code, and it works like a charm, but I believe it avoids the Server-side rendering?

```
axios.get('https://jsonplaceholder.typicode.com/todos/1')
.then((res) => ( this.faketitle = res.data.title ))
```

**Comment by baxgas** [comment]
OK, I've got the solution, the asyncData works only on page type of template and I tried on the layout...

**Comment by baxgas** [comment]
But, in case of the menu, which should be fetched dynamically from the WP REST json, if the asyncData doesn't work on the layout/component level isn't it a bit SEO unfriendly? Or it doesn't matter if the pages themselves are loaded correctly?

**Comment by northosts** [comment]
That's more a question for Nuxtjs, but you're right asyncData does not work in layouts. Great that you found the solution. 
Not entirely sure what you mean with the second part of your question, you are always loading layout and components with pages, so everything will be loaded dynamically.
