### ISSUE TITLE
Using Makefile instead of gulp ?

### ISSUE THREAD

**Issue by edimitchel** [northosts/wuxt#8]
IMHO, Gulp is an outdated (or overcomplicated) solution for tasks runners.

Makefiles is old but work perfectly.

**Comment by northosts** [comment]
Thanks for the feedback! Agree on gulp being outdated, wanted to keep JavaScript as scripting language, though. Now I've removed Gulp and completely replaced it with npm-scripts. Check the [updated documentation](https://github.com/northosts/wuxt#scripts).
